sampletable: 'config/test_sampletable.tsv'

patterns: 'config/rnaseq_patterns.yaml'

# Which key in the `references` dict below to use
organism: 'dmel'

# If not specified here, use the environment variable REFERENCES_DIR.
references_dir: '../lcdb-references'

aligner:
  index: 'hisat2'
  tag: 'r6-26_and_ercc'

rrna:
  index: 'bowtie2'
  tag: 'rRNA'

gtf:
  tag: "r6-26_and_ercc"

gtf_db:
  tag: "r6-26"

fastq_screen:
  - label: rRNA
    organism: dmel
    tag: rRNA
  - label: PhiX
    organism: phix
    tag: default
  - label: Fly
    organism: dmel
    tag: r6-26
  - label: Wolbachia
    organism: wolbachia
    tag: default
  - label: Yeast
    organism: sacCer
    tag: sacCer3
  - label: Pombe
    organism: spombe
    tag: ucsc_41
  - label: Ecoli
    organism: ecoli
    tag: default
  - label: Human
    organism: human
    tag: gencode-v28
  - label: Mouse
    organism: mouse
    tag: gencode_m18
  - label: Rat
    organism: rat
    tag: ucsc_rn6


# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.

include_references:
  - ../config/reference_configs/Drosophila_melanogaster.yaml
  - ../config/reference_configs/PhiX.yaml
  - ../config/reference_configs/Wolbachia_endosymbiont_of_Drosophila_melanogaster.yaml
  - ../config/reference_configs/Saccharomyces_cerevisiae.yaml
  - ../config/reference_configs/Schizosaccharomyces_pombe.yaml
  - ../config/reference_configs/Escherichia_coli.yaml
  - ../config/reference_configs/Homo_sapiens.yaml
  - ../config/reference_configs/Mus_musculus.yaml
  - ../config/reference_configs/Rattus_norvegicus.yaml
