name: s2rnai
dependencies:
- anaconda-client=1.5.1=py35_0
- argh=0.26.2=py35_0
- backports.shutil_get_terminal_size=1.0.0=py35_0
- biopython=1.68=py35_0
- blas=1.1=openblas
- cairo=1.12.18=8
- clyent=1.2.2=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- gettext=0.19.7=1
- glib=2.48.0=4
- harfbuzz=1.0.6=0
- icu=56.1=4
- ipykernel=4.5.0=py35_0
- ipyparallel=5.2.0=py35_1
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_2
- jedi=0.9.0=py35_1
- jinja2=2.8=py35_1
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_contrib_core=0.3.0=py35_0
- jupyter_contrib_nbextensions=0.2.0=py35_0
- jupyter_core=4.2.0=py35_0
- jupyter_nbextensions_configurator=0.2.2=py35_0
- libffi=3.2.1=2
- libgfortran=3.0.0=1
- libiconv=1.14=3
- libpng=1.6.24=0
- libsodium=1.0.10=0
- libtiff=4.0.6=6
- libxml2=2.9.4=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_0
- mistune=0.7.3=py35_0
- mmtf-python=1.0.2=py35_0
- msgpack-python=0.4.7=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- ncurses=5.9=9
- notebook=4.2.3=py35_0
- numpy=1.11.2=py35_blas_openblas_200
- openblas=0.2.18=5
- openssl=1.0.2j=0
- pandas=0.19.0=np111py35_0
- pango=1.40.1=0
- path.py=8.2.1=py35_0
- pathtools=0.1.2=py35_0
- patsy=0.4.1=py35_0
- pcre=8.39=0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.4.1=py35_0
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.7=py35_0
- psutil=4.3.1=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_1
- pyparsing=2.1.9=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=2
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- pyyaml=3.12=py35_0
- pyzmq=15.4.0=py35_0
- qgrid=0.3.2=py35_0
- qt=4.8.7=4
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- reportlab=3.3.0=py35_0
- requests=2.11.1=py35_0
- scipy=0.18.1=np111py35_blas_openblas_200
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=1
- statsmodels=0.6.1=np111py35_1
- terminado=0.6=py35_0
- tk=8.5.19=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- watchdog=0.8.3=py35_0
- watermark=1.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_3
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - greenlet==0.4.10
  - ipycache==0.1.6.dev0
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.0
  - jupyter-core==4.2.0
  - jupyter-nbextensions-configurator==0.2.2
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - neovim==0.1.10
  - prompt-toolkit==1.0.7

