name: s2rnai
channels: !!python/tuple
- jfear
- lcdb
- bioconda
- r
- defaults
- conda-forge
dependencies:
- anaconda-client=1.6.0
- bioconda::argh=0.26.2
- bioconda::biopython=1.68
- bioconda::expat=2.1.0
- bioconda::gffutils=0.8.7.1
- bioconda::jpeg=9b
- bioconda::libxml2=2.9.3
- bioconda::meme=4.11.1
- bioconda::mmtf-python=1.0.5
- bioconda::pathtools=0.1.2
- bioconda::python-dateutil=2.3
- bioconda::watchdog=0.8.3
- clyent=1.2.2
- dbus=1.10.10
- decorator=4.0.11
- entrypoints=0.2.2
- fontconfig=2.12.1
- freetype=2.5.5
- glib=2.50.2
- gst-plugins-base=1.8.0
- gstreamer=1.8.0
- icu=54.1
- ipykernel=4.5.2
- ipyparallel=5.2.0
- ipython=5.1.0
- ipython_genutils=0.1.0
- ipywidgets=5.2.2
- jbig=2.1
- jedi=0.9.0
- jfear::ipycache=0.1.6dev
- jfear::neovim=0.1.12
- jfear::watermark=1.3.1
- jinja2=2.9.4
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.4.0
- jupyter_console=5.0.0
- jupyter_core=4.2.1
- libffi=3.2.1
- libgcc=5.2.0
- libgfortran=3.0.0
- libiconv=1.14
- libpng=1.6.27
- libsodium=1.0.10
- libtiff=4.0.6
- libxcb=1.12
- lcdb::lcdblib
- lcdb::snakemake=3.10.0.post1
- markupsafe=0.23
- mistune=0.7.3
- mkl=2017.0.1
- msgpack-python=0.4.8
- nb_anacondacloud=1.2.0
- nb_conda=2.0.0
- nb_conda_kernels=2.0.0
- nbconvert=4.2.0
- nbformat=4.2.0
- nbpresent=3.0.2
- notebook=4.3.1
- numpy=1.11.3
- openssl=1.0.2j
- pandas=0.19.2
- path.py=10.0
- pcre=8.39
- pexpect=4.2.1
- pickleshare=0.7.4
- pillow=4.0.0
- pip=9.0.1
- prompt_toolkit=1.0.9
- ptyprocess=0.5.1
- pygments=2.1.3
- pyqt=5.6.0
- python=3.5.2
- pytz=2016.10
- pyyaml=3.12
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.2.1
- readline=6.2
- reportlab=3.3.0
- requests=2.12.4
- scipy=0.18.1
- setuptools=27.2.0
- simplegeneric=0.8.1
- sip=4.18
- six=1.10.0
- sqlite=3.13.0
- terminado=0.6
- tk=8.5.18
- tornado=4.4.2
- traitlets=4.3.1
- wcwidth=0.1.7
- wheel=0.29.0
- widgetsnbextension=1.2.6
- xz=5.2.2
- yaml=0.1.6
- zeromq=4.1.5
- zlib=1.2.8
