name: s2rnai
channels:
  - conda-forge
  - bioconda
  - defaults
  - lcdb
dependencies:
  - biopython=1.76
  - bowtie2=2.3.5
  - cutadapt=2.7
  - feather-format=0.4.0
  - gffutils=0.10.1
  - hisat2=2.1.0
  - matplotlib=3.1.2
  - multiqc=1.8
  - numpy=1.17.3
  - pandas=0.25.3
  - pip=20.1.1
  - pybedtools=0.8.1
  - python=3.7.6
  - python-dotenv=0.13.0
  - pyranges=0.0.67
  - pysam=0.15.3
  - r-base=3.5.1
  - samtools=1.9
  - scipy=1.4.1
  - seaborn=0.9.0
  - snakemake=5.9.1
  - sra-tools=2.10.0
  - subread=1.6.4
  - pip:
    - geoparse==2.0.1