name: s2rnai
channels:
  - conda-forge
  - bioconda
  - defaults
  - lcdb
dependencies:
  - feather-format=0.4.0
  - matplotlib=3.1.2
  - numpy=1.17.3
  - pandas=0.25.3
  - python=3.7.6
  - pyranges=0.0.67
  - pysam=0.15.3
  - scipy=1.4.1
  - seaborn=0.9.0
  - snakemake=5.9.1
