channels:
  - bioconda
  - conda-forge

dependencies:
  - bioconductor-deseq2
  - bioconductor-annotationhub
  - bioconductor-org.hs.eg.db
  - bioconductor-org.dm.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-genomicfeatures
  - bioconductor-sva
  - bioconductor-tximport
  - pandoc
  - r-codetools
  - r-dt
  - r-knitrbootstrap
  - r-knitr
  - r-pheatmap
  - r-readr
  - r-rmarkdown
