name: s2rnai
dependencies:
- anaconda-client=1.5.1
- argh=0.26.2
- backports.shutil_get_terminal_size=1.0.0
- biopython=1.68
- blas=1.1
- cairo=1.12.18
- cffi=1.8.3
- cloog=0.18.0
- clyent=1.2.2
- cryptography=1.5.2
- cycler=0.10.0
- decorator=4.0.10
- docutils=0.12
- dropbox=5.2.1
- entrypoints=0.2.2
- expat=2.1.0
- filechunkio=1.8
- fontconfig=2.11.1
- freetype=2.6.3
- ftputil=3.2
- gcc=4.8.5
- gettext=0.19.7
- ghostscript=9.18
- glib=2.48.0
- gmp=6.1.1
- harfbuzz=1.0.6
- icu=56.1
- idna=2.1
- ipykernel=4.5.0
- ipyparallel=5.2.0
- ipython=5.1.0
- ipython_genutils=0.1.0
- ipywidgets=5.2.2
- isl=0.12.2
- jedi=0.9.0
- jinja2=2.8
- jpeg=9b
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.4.0
- jupyter_console=5.0.0
- jupyter_contrib_core=0.3.0
- jupyter_contrib_nbextensions=0.2.0
- jupyter_core=4.2.0
- jupyter_nbextensions_configurator=0.2.2
- libffi=3.2.1
- libgcc=5.2.0
- libgfortran=3.0.0
- libiconv=1.14
- libpng=1.6.24
- libsodium=1.0.10
- libtiff=4.0.6
- libxml2=2.9.4
- libxslt=1.1.29
- markupsafe=0.23
- matplotlib=1.5.3
- meme=4.11.1
- mistune=0.7.3
- mmtf-python=1.0.2
- mpc=1.0.3
- mpfr=3.1.4
- msgpack-python=0.4.7
- nb_conda=2.0.0
- nb_conda_kernels=2.0.0
- nbconvert=4.2.0
- nbformat=4.1.0
- ncurses=5.9
- notebook=4.2.3
- numpy=1.11.2
- openblas=0.2.18
- openssl=1.0.2j
- pandas=0.19.0
- pango=1.40.1
- paramiko=2.0.2
- path.py=8.2.1
- pathtools=0.1.2
- patsy=0.4.1
- pcre=8.39
- perl=5.22.0
- perl-digest-hmac=1.03
- perl-encode-locale=1.05
- perl-file-listing=6.04
- perl-html-parser=3.72
- perl-html-tagset=3.20
- perl-http-cookies=6.01
- perl-http-daemon=6.01
- perl-http-date=6.02
- perl-http-message=6.11
- perl-http-negotiate=6.01
- perl-io-html=1.001
- perl-io-socket-ssl=2.024
- perl-libwww-perl=6.15
- perl-lwp-mediatypes=6.02
- perl-net-http=6.09
- perl-net-ssleay=1.74
- perl-ntlm=1.09
- perl-threaded=5.22.0
- perl-uri=1.71
- perl-www-robotrules=6.02
- perl-xml-parser=2.44
- pexpect=4.2.1
- pickleshare=0.7.4
- pillow=3.4.1
- pip=8.1.2
- pixman=0.32.6
- prompt_toolkit=1.0.7
- psutil=4.3.1
- ptyprocess=0.5.1
- pyasn1=0.1.9
- pycparser=2.14
- pygments=2.1.3
- pyparsing=2.1.9
- pyqt=4.11.4
- pysftp=0.2.8
- python=3.5.2
- python-dateutil=2.5.3
- pytz=2016.7
- pyyaml=3.12
- pyzmq=15.4.0
- qgrid=0.3.2
- qt=4.8.7
- qtconsole=4.2.1
- readline=6.2
- reportlab=3.3.0
- requests=2.11.1
- scipy=0.18.1
- seaborn=0.7.1
- setuptools=27.2.0
- simplegeneric=0.8.1
- sip=4.18
- six=1.10.0
- snakemake=3.8.2
- sqlite=3.13.0
- statsmodels=0.6.1
- terminado=0.6
- tk=8.5.19
- tornado=4.4.2
- traitlets=4.3.1
- urllib3=1.16
- watchdog=0.8.3
- watermark=1.3.1
- wcwidth=0.1.7
- wheel=0.29.0
- widgetsnbextension=1.2.6
- wrapt=1.10.8
- xz=5.2.2
- yaml=0.1.6
- zeromq=4.1.5
- zlib=1.2.8
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - greenlet==0.4.10
  - ipycache==0.1.6.dev0
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.0
  - jupyter-core==4.2.0
  - jupyter-nbextensions-configurator==0.2.2
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - neovim==0.1.10
  - prompt-toolkit==1.0.7

