__default__:
  mem: '4g'
  time: '4:00:00'
  gres: "lscratch:20"
  partition: 'niddk,norm'
  threads: 2

fimo:
  time: '72:00:00'

bowtie2_index:
  mem: '32g'

hisat2_index:
  mem: '32g'

hisat2:
  mem: '32g'

fastq_screen:
  mem: '32g'

kallisto:
  mem: '32g'

markduplicates:
  mem: '32g'

bowtie2_map_to_reduced_genome:
  mem: '32g'
